// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV0paHgRolrLobbjcwclkGPpPITNad2lc',
    appId: '1:350920702739:web:09247d60d34a2dd45b38e6',
    messagingSenderId: '350920702739',
    projectId: 'nutrition-95959',
    authDomain: 'nutrition-95959.firebaseapp.com',
    storageBucket: 'nutrition-95959.firebasestorage.app',
    measurementId: 'G-9W1CQMXSTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChNBFNxBJpiuqSPQrpikPgVhUiyZsHOQo',
    appId: '1:350920702739:android:14c91d573ad951d15b38e6',
    messagingSenderId: '350920702739',
    projectId: 'nutrition-95959',
    storageBucket: 'nutrition-95959.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHus08dWEuIVdpOtqFOmxG6s88dwHO-OU',
    appId: '1:350920702739:ios:7ba5cc81032a10be5b38e6',
    messagingSenderId: '350920702739',
    projectId: 'nutrition-95959',
    storageBucket: 'nutrition-95959.firebasestorage.app',
    iosBundleId: 'com.example.nutrition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHus08dWEuIVdpOtqFOmxG6s88dwHO-OU',
    appId: '1:350920702739:ios:7ba5cc81032a10be5b38e6',
    messagingSenderId: '350920702739',
    projectId: 'nutrition-95959',
    storageBucket: 'nutrition-95959.firebasestorage.app',
    iosBundleId: 'com.example.nutrition',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV0paHgRolrLobbjcwclkGPpPITNad2lc',
    appId: '1:350920702739:web:9df2be9c82bfcf2c5b38e6',
    messagingSenderId: '350920702739',
    projectId: 'nutrition-95959',
    authDomain: 'nutrition-95959.firebaseapp.com',
    storageBucket: 'nutrition-95959.firebasestorage.app',
    measurementId: 'G-QK7P5BBPFM',
  );
}
